### ISSUE TITLE
PCV, 2.80, points somehow lost depth sorting, in fact, looks inverted now

### ISSUE THREAD

**Issue by uhlik** [uhlik/bpy#10]

**Comment by uhlik** [comment]
blender-2.80.0-git20190625.c0c1b4542f39 25.6.2019

**Comment by VupliDerts** [comment]
I can confirm that the depth sorting appears to be awry on the latest 2.8:
**Blender Version**
Broken: version: 2.80 (sub 74), branch: master, commit date: 2019-06-25 23:26, hash: `rBabaf6b106d3a`
Worked: (optional)

**But** it appears to work fine on this older build of 2.8, so maybe its an API compatibility issue?
**Blender Version**
Broken: version: 2.80 (sub 74), branch: blender2.7, commit date: 2019-06-17 21:07, hash: `rB741641f4c3b8`
Worked: (optional)

**Comment by uhlik** [comment]
see here: https://developer.blender.org/T66148
will update it soon..

**Comment by uhlik** [comment]
fixed
