### ISSUE TITLE
Rendering Point Cloud Visualizer question

### ISSUE THREAD

**Issue by SamDot37** [uhlik/bpy#11]
Hey, complete git-hub noob here. 

I was looking for a ply.visualizer/renderer pretty long and your addon seems to be amazing! 
But i have real troubles to get the rendering engine to work. Honestly only because i'm a ultranoob in working with third-party plugins.. 
I tried to it like you mention it in the how-to-file but i dont get where i should find that "properties" button
Sorry for my noobish question haha

**Comment by uhlik** [comment]
i guess you are searching for so called 'buttons' view, it uses output resolution for regular rendering that you set there. i think i'll move those properties to addon panel, it's confusing a bit..

**Comment by SamDot37** [comment]
Thanks for the answer! 
But so it uses the resolution i would normally use for a basic still? 
And i still don't get where to save a render..

**Comment by uhlik** [comment]
in path specified in other panel there "Output" with suffix specified in addon
