### ISSUE TITLE
Some feature/improvements ideas

### ISSUE THREAD

**Issue by jvaloos** [uhlik/bpy#15]
Hi,

first, thank you for great plugin!

I have some feature/improvements ideas:
- progress-bar during rendering animation
- rendering time counter
- render above 10000x10000 resolution

thanks

**Comment by uhlik** [comment]
hi,
progress bar is available only for render engines. this is not a render engine, it just lets opengl write to texture and saves result as image. i can add some logging to terminal where you could check progress if you start blender from there. 10000 limit, there is no limit set (i think), i just tried and result was distorted, happens the same to you? i can have a look, but i'm afraid it will something related to blender itself or hardware. it's opengl, it's like you want your gpu to draw 10k+ x 10k+ screen

**Comment by jvaloos** [comment]
I was hoping that if animation is an iterative saving of rendered frames, there is a chance to display statistics about this process...
Following the terminal is not so convenient, but I think it's enough. Maybe there is a chance to estimate the remaining time of rendering?  
About 10K limit: In my case, the result is distorted too. I am wondering about this round number (10,000) - not so informatics limit :)

**Comment by mecowhy** [comment]
Hi, 
+1 for some progress tracking , maybe if progressbar is not possible some other control (like text label) could show current_frame/total_frames value during rendering ?

**Comment by mecowhy** [comment]
ok I'll answer myslef, looks like console output is the only solution to this problem, for reasons described [here](https://blender.stackexchange.com/questions/7468/blender-not-responding-while-running-my-script)

**Comment by uhlik** [comment]
image distortion is blender limitation or overlook from the time maximum render size was 10k. i am using this: https://docs.blender.org/api/blender2.8/bpy.types.Image.html#bpy.types.Image.scale to resize image after render even when Supersampling is disabled, so as temporal fix, comment out line 6383: `# image.scale(width, height)` and don't use Supersampling
will add some logging and maybe even time estimate later

**Comment by uhlik** [comment]
logging is in, scaling bug (might be feature?) reported..
log include elapsed and remaining time, and individual frames time, looks like this:
```PCV: Frame completed in 0:00:00.303579.
PCV: Frame: 1 (1/50) | Time: 0:00:00 | Remaining: 0:00:14
PCV: Frame completed in 0:00:00.286108.
PCV: Frame: 2 (2/50) | Time: 0:00:00 | Remaining: 0:00:14
PCV: Frame completed in 0:00:00.299350.
PCV: Frame: 3 (3/50) | Time: 0:00:00 | Remaining: 0:00:13
PCV: Frame completed in 0:00:00.292893.
PCV: Frame: 4 (4/50) | Time: 0:00:01 | Remaining: 0:00:13
PCV: Frame completed in 0:00:00.285406.
PCV: Frame: 5 (5/50) | Time: 0:00:01 | Remaining: 0:00:13
...
```

**Comment by uhlik** [comment]
ok, it was my mistake and pretty stupid one. anyway, it should work now. but, on my machine anything large than 16384x16384 fails with exception and 16383 starts, but after while crashes.. was not patient enough to check which will result in something.. so, i guess there are some limitations..

**Comment by jvaloos** [comment]
There is an error in calculating the remaining time:
- cannot be started from 0 frame (dividing by 0 error)
- when the animation is started from frame above 1, the remaining time is negative (for ex. 3-5)
:)

**Comment by uhlik** [comment]
embarrassing.. should be fixed now
