### ISSUE TITLE
Render with Point Cloud Visualizer

### ISSUE THREAD

**Issue by clementvalla** [uhlik/bpy#18]
In Blender 2.80 I get  an error when I try to render points with the Point Cloud Visualizer:
'Context' object has no attribute 'evaluated_depsgraph_get'

**Comment by uhlik** [comment]
can you attach some file so i can replicate it? it works for me as expected. 'evaluated_depsgraph_get' in render is only used to get scene camera view matrix. do you have some non standard camera setup?

**Comment by clementvalla** [comment]
I was trying to use an orthographic camera, but deleting it and setting a new camera, and restarting a completely new file all led to the same issue.

Ok, here's a link to a blend file and the associated ply file:
https://www.dropbox.com/s/1bwecyjf1yu2217/tests.blend?dl=0
https://www.dropbox.com/s/5kpdbfxvaag9vfy/191022_fort_greene_flowers_05_med_density.ply?dl=0

**Comment by uhlik** [comment]
hm, it works (i only change output path), with my ply, loaded ply should not have any influence on context/depsgraph.. i download the ply too, to see if something goes wrong.. do you have official final 2.80 build?

**Comment by clementvalla** [comment]
Ok, thanks so much, and apologies - I downloaded Blender again and now everything is working.
I have like 5 different version of Blender on my laptop and must have gotten them mixed up. Apologies again.

**Comment by uhlik** [comment]
no problem
