### ISSUE TITLE
Import Metashape XML error

### ISSUE THREAD

**Issue by solosails** [uhlik/bpy#19]
Hi, (first, thanks! awesome tools!)

Software:
Win 10 64
Blender: 2.81a
Metashape : 1.5.5
Import Agisoft PhotoScan Cameras : 0.1.3

When importing I get this error:

Traceback (most recent call last):
  File "C:\Users\Woody\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_photoscan_cameras.py", line 874, in execute
    o = PSCXMLImport(**d)
  File "C:\Users\Woody\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_photoscan_cameras.py", line 674, in __init__
    self._make()
  File "C:\Users\Woody\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_photoscan_cameras.py", line 697, in _make
    self.psc = PSCMakeCameras(self.xml_path, self.matrix, self.camera_draw_size, do_planes, self.chunk_regions, self.correct_principal_point, )
  File "C:\Users\Woody\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_photoscan_cameras.py", line 372, in __init__
    self._make()
  File "C:\Users\Woody\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_photoscan_cameras.py", line 377, in _make
    self._load_parse_xml()
  File "C:\Users\Woody\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_photoscan_cameras.py", line 410, in _load_parse_xml
    ch = PSCChunk(chunk, "chunk-{0}".format(i))
  File "C:\Users\Woody\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_photoscan_cameras.py", line 329, in __init__
    sd = PSCSensor(s)
  File "C:\Users\Woody\AppData\Roaming\Blender Foundation\Blender\2.81\scripts\addons\io_import_photoscan_cameras.py", line 173, in __init__
    self.calibration['type'] = cal.attrib["type"]
UnboundLocalError: local variable 'cal' referenced before assignment

location: <unknown location>:-1

Thanks in advance

**Comment by uhlik** [comment]
hi, can you attach some example xml file? was the scan completely processed? looks like your xml is missing data from sensor calibration which i never encountered with my scans.

**Comment by solosails** [comment]
Hi, Thanks for taking time to reply .
this is the XML file I got an error with ...

<?xml version="1.0" encoding="UTF-8"?>
<document version="1.5.0">
  <chunk label="Chunk 1" enabled="true">
    <sensors next_id="2">
      <sensor id="0" label="iPhone 7 (3.99mm)" type="frame">
        <resolution width="4032" height="3024"/>
        <property name="pixel_width" value="0.00122331203988957"/>
        <property name="pixel_height" value="0.00122331203988957"/>
        <property name="focal_length" value="3.99"/>
        <property name="layer_index" value="0"/>
        <bands>
          <band label="Red"/>
          <band label="Green"/>
          <band label="Blue"/>
        </bands>
        <data_type>uint8</data_type>
        <rotation fixed="true"/>
        <location fixed="true"/>
      </sensor>
      <sensor id="1" label="iPhone 7 (3.99mm)" type="frame">
        <resolution width="4032" height="3024"/>
        <property name="pixel_width" value="0.00122331203988957"/>
        <property name="pixel_height" value="0.00122331203988957"/>
        <property name="focal_length" value="3.99"/>
        <property name="layer_index" value="0"/>
        <bands>
          <band label="Red"/>
          <band label="Green"/>
          <band label="Blue"/>
        </bands>
        <data_type>uint8</data_type>
        <calibration type="frame" class="adjusted">
          <resolution width="4032" height="3024"/>
          <f>3268.30117351641</f>
          <cx>-44.6362088232318</cx>
          <cy>15.7285655313915</cy>
          <k1>0.171495870829136</k1>
          <k2>-0.780531697949272</k2>
          <k3>1.12496581610789</k3>
          <p1>-0.00153194338570767</p1>
          <p2>-0.000565686250784563</p2>
        </calibration>
        <covariance>
          <params>f cx cy k1 k2 k3 p1 p2</params>
          <coeffs>8.5088488282806274e-001 7.6864746293136055e-002 -4.3300667715338449e-002 1.7047734993313321e-004 -6.1227409478562390e-004 1.6812378285214395e-003 1.7172448638438189e-005 -2.5101354536514408e-006 7.6864746293136055e-002 8.6318429353126314e-001 6.2809057036219501e-002 -4.4149386315981639e-005 2.7510851525938869e-004 -5.3840376917796732e-004 6.6498834222720158e-005 5.6603455315035356e-006 -4.3300667715338449e-002 6.2809057036219501e-002 8.9808037732573365e-001 -1.5278642795814333e-005 5.5524935196796413e-005 -1.2038568848070237e-004 4.3218947632834882e-006 7.2819582786557763e-005 1.7047734993313321e-004 -4.4149386315981639e-005 -1.5278642795814333e-005 5.0119101677234474e-007 -2.6361047484616045e-006 4.3344666381279054e-006 -7.7824021516768876e-010 -1.3651215306284624e-009 -6.1227409478562390e-004 2.7510851525938869e-004 5.5524935196796413e-005 -2.6361047484616045e-006 1.4930861531752925e-005 -2.5179752207594803e-005 1.1592589939181843e-008 5.3459311966723648e-009 1.6812378285214395e-003 -5.3840376917796732e-004 -1.2038568848070237e-004 4.3344666381279054e-006 -2.5179752207594803e-005 4.4259080802297264e-005 -1.5340514350855624e-008 -1.0602130137806956e-008 1.7172448638438189e-005 6.6498834222720158e-005 4.3218947632834882e-006 -7.7824021516768876e-010 1.1592589939181843e-008 -1.5340514350855624e-008 6.4166440093525403e-009 1.7216489847486557e-010 -2.5101354536514408e-006 5.6603455315035356e-006 7.2819582786557763e-005 -1.3651215306284624e-009 5.3459311966723648e-009 -1.0602130137806956e-008 1.7216489847486557e-010 6.8751447476945246e-009</coeffs>
        </covariance>
      </sensor>
    </sensors>
    <cameras next_id="20" next_group_id="0">
      <camera id="1" sensor_id="1" label="Photo 12-12-2019, 11 50 02.jpg">
        <transform>1 0 0 0 0 -1.0000000000000000e+000 0 0 0 0 -1.0000000000000000e+000 0 0 0 0 1</transform>
        <orientation>6</orientation>
      </camera>
      <camera id="2" sensor_id="1" label="Photo 12-12-2019, 11 50 03.jpg">
        <transform>9.9966540118123204e-001 -2.5718071903636577e-002 2.7688370710483487e-003 2.2411219259369930e-001 -2.5866681880557199e-002 -9.9400917971062852e-001 1.0619164477252147e-001 1.0846565707139166e+000 2.1205109920007735e-005 -1.0622773380131344e-001 -9.9434182659776527e-001 3.1211414409873067e-001 0 0 0 1</transform>
        <rotation_covariance>7.8733569642883399e-009 8.5288944188790401e-010 -1.5335827477911526e-009 8.5288944188790401e-010 4.3596015102445667e-009 6.2053163165553587e-011 -1.5335827477911524e-009 6.2053163165553355e-011 1.8652968473099689e-009</rotation_covariance>
        <location_covariance>1.2183749438696673e-006 3.6944390117322085e-007 -6.7439252511157207e-007 3.6944390117322085e-007 1.5260091100884466e-006 -2.3315209383414349e-009 -6.7439252511157207e-007 -2.3315209383414349e-009 7.4693023957899128e-007</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="3" sensor_id="1" label="Photo 12-12-2019, 11 50 04.jpg">
        <transform>9.9753205659340383e-001 -6.2207773434010780e-002 3.2557472151845956e-002 5.1985727072975230e-001 -6.6244937169411613e-002 -9.8753176490028582e-001 1.4280273671168925e-001 2.9654036340850287e+000 2.3268097643686873e-002 -1.4460707533627148e-001 -9.8921554243487997e-001 6.4165431255552496e-001 0 0 0 1</transform>
        <rotation_covariance>2.0090483846046615e-008 1.4286105851382468e-009 -1.5620214350725961e-009 1.4286105851382470e-009 7.9170961817767958e-009 6.5029293969427477e-010 -1.5620214350725967e-009 6.5029293969427498e-010 3.8459111441206715e-009</rotation_covariance>
        <location_covariance>2.1172133365793565e-006 6.7828253165334487e-007 -1.2334013639743491e-006 6.7828253165334487e-007 3.0958592150930422e-006 1.3075589519740015e-007 -1.2334013639743491e-006 1.3075589519740015e-007 1.7343112418065609e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="4" sensor_id="1" label="Photo 12-12-2019, 11 50 06.jpg">
        <transform>9.9091088391750182e-001 -1.2102479972500274e-001 5.8724934954059477e-002 9.3953828128013439e-001 -1.3130802383982346e-001 -9.6504261814402559e-001 2.2682801423326171e-001 5.7101137660371180e+000 2.9220249983802606e-002 -2.3247740324007257e-001 -9.7216276105065691e-001 1.2764313990056093e+000 0 0 0 1</transform>
        <rotation_covariance>4.8170593838699554e-008 2.1451987994020887e-009 9.5076917808546533e-010 2.1451987994020891e-009 1.5054799278556903e-008 2.7685660244455839e-009 9.5076917808546533e-010 2.7685660244455831e-009 8.1204675351894538e-009</rotation_covariance>
        <location_covariance>3.9187401163668022e-006 1.3354869979185318e-006 -1.9271243879324784e-006 1.3354869979185318e-006 6.2401492673629611e-006 9.5747097706806800e-007 -1.9271243879324784e-006 9.5747097706806800e-007 4.3033531978922286e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="5" sensor_id="1" label="Photo 12-12-2019, 11 50 07.jpg">
        <transform>9.7961324641659608e-001 -1.8704745585621421e-001 7.3288039289200163e-002 1.5171040514018181e+000 -2.0059320275338655e-001 -9.3065349698342925e-001 3.0601705109626448e-001 8.8243880500839875e+000 1.0966059195375719e-002 -3.1447943940778178e-001 -9.4920094170596547e-001 2.1192302172453035e+000 0 0 0 1</transform>
        <rotation_covariance>1.0540741514782657e-007 6.5831367582120538e-011 3.4352741845446497e-009 6.5831367582113817e-011 2.6207121617029498e-008 3.8504694053416789e-009 3.4352741845446513e-009 3.8504694053416781e-009 1.7197605699864893e-008</rotation_covariance>
        <location_covariance>6.9112924131115073e-006 3.2604034223210476e-006 -2.6091277014020232e-006 3.2604034223210476e-006 1.3812830700218231e-005 3.2261825299113034e-006 -2.6091277014020232e-006 3.2261825299113034e-006 9.2174424727114619e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="6" sensor_id="1" label="Photo 12-12-2019, 11 50 09.jpg">
        <transform>9.8108401863625705e-001 -1.8995333639585402e-001 -3.7307886145110672e-002 -7.4941121545631684e-001 -1.6420439139626292e-001 -9.1866250714444031e-001 3.5929947928333289e-001 8.6466401273413229e+000 -1.0252349107748888e-001 -3.4637685829046733e-001 -9.3247627627629681e-001 2.0546494266019839e+000 0 0 0 1</transform>
        <rotation_covariance>9.5574334513494970e-008 -1.9797304445445259e-008 -3.5070838053858394e-009 -1.9797304445445259e-008 3.5069464133869471e-008 6.7319020994468285e-010 -3.5070838053858402e-009 6.7319020994468450e-010 9.2890241244673233e-009</rotation_covariance>
        <location_covariance>8.5280948452711907e-006 9.9510303621474319e-007 -3.0070050719283308e-006 9.9510303621474319e-007 1.3094796688421494e-005 2.4387017549521390e-006 -3.0070050719283308e-006 2.4387017549521390e-006 7.0053803588105292e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="7" sensor_id="1" label="Photo 12-12-2019, 11 50 10.jpg">
        <transform>9.8476759146154491e-001 -1.6942447619962861e-001 -3.9091401503506949e-002 -2.6607537863779336e+000 -1.5142052808773060e-001 -9.4614462390757814e-001 2.8615061475457426e-001 5.8564956735231366e+000 -8.5467037392551237e-002 -2.7587261102775196e-001 -9.5738690611689015e-001 4.1679668078417687e-001 0 0 0 1</transform>
        <rotation_covariance>4.5382759607470506e-008 -1.9801078492619617e-008 -1.6939923675027284e-009 -1.9801078492619620e-008 2.8350203897260725e-008 -1.6924144728729528e-009 -1.6939923675027290e-009 -1.6924144728729532e-009 4.7233615960397808e-009</rotation_covariance>
        <location_covariance>4.3929380380209624e-006 -7.3310522808857027e-008 -1.2548127883623292e-006 -7.3310522808857027e-008 6.2839575280319217e-006 2.9035607117591890e-007 -1.2548127883623292e-006 2.9035607117591890e-007 1.9539210999274816e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="8" sensor_id="1" label="Photo 12-12-2019, 11 50 11.jpg">
        <transform>9.8661217702233617e-001 -1.6212002584643634e-001 -1.7706195830728931e-002 -3.2561616701138356e+000 -1.5274190281701336e-001 -9.5663073012956268e-001 2.4804749000064175e-001 3.2375297683652535e+000 -5.7151756535414926e-002 -2.4202219607162292e-001 -9.6858604849212304e-001 -8.2316193923737357e-001 0 0 0 1</transform>
        <rotation_covariance>2.2428536561423582e-008 -1.1084544426344768e-008 -1.6858052801790338e-009 -1.1084544426344768e-008 2.4501558791624702e-008 -2.8467716203953843e-009 -1.6858052801790336e-009 -2.8467716203953843e-009 4.5395794604971937e-009</rotation_covariance>
        <location_covariance>3.5713490290623618e-006 -2.8920216570250333e-007 -6.9401592151755374e-007 -2.8920216570250333e-007 3.6950477522533461e-006 -2.4123539775600892e-007 -6.9401592151755374e-007 -2.4123539775600892e-007 9.7856081239289706e-007</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="9" sensor_id="1" label="Photo 12-12-2019, 11 50 12.jpg">
        <transform>9.9161229297789721e-001 -1.2887794583628531e-001 -9.7742259098669883e-003 -3.7482750487243264e+000 -1.2354931813411997e-001 -9.6738429879657495e-001 2.2114064400388517e-001 3.1277836567367717e-001 -3.7955584618229940e-002 -2.1807818212484867e-001 -9.7519294505108578e-001 -2.1595879981891835e+000 0 0 0 1</transform>
        <rotation_covariance>1.0497472662831191e-008 -3.6369065147557748e-009 -2.2209716280563767e-009 -3.6369065147557748e-009 2.2791112478563085e-008 -3.8862113546838883e-009 -2.2209716280563767e-009 -3.8862113546838875e-009 5.0638092527465592e-009</rotation_covariance>
        <location_covariance>3.4959979826417555e-006 -5.7121263608551820e-008 -3.0729756331211142e-007 -5.7121263608551820e-008 2.3173488031153675e-006 -1.3102900508475925e-007 -3.0729756331211142e-007 -1.3102900508475925e-007 1.3231568852594094e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="10" sensor_id="1" label="Photo 12-12-2019, 11 50 13.jpg">
        <transform>9.9828006640017719e-001 -5.7691997019338810e-002 -1.0418373576451962e-002 -4.3383844540064427e+000 -5.5173298017001784e-002 -9.8462629627608933e-001 1.6573160189764147e-001 -3.5628156473838062e+000 -1.9819591670491542e-002 -1.6487173851679893e-001 -9.8611586217059910e-001 -3.4023959750721007e+000 0 0 0 1</transform>
        <rotation_covariance>2.3954450920468730e-008 7.1372349074245855e-009 -2.1811583177601913e-010 7.1372349074245847e-009 3.3926005683281488e-008 -4.3730883446791373e-009 -2.1811583177601902e-010 -4.3730883446791389e-009 7.8792505232250787e-009</rotation_covariance>
        <location_covariance>6.6806815976571259e-006 8.3245870663726132e-007 2.7507695855504177e-007 8.3245870663726132e-007 5.8041034310556546e-006 1.6752528561667640e-006 2.7507695855504177e-007 1.6752528561667640e-006 3.0426562554109485e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="11" sensor_id="1" label="Photo 12-12-2019, 11 50 15.jpg">
        <transform>9.9847122292399759e-001 -5.2833840421249591e-002 -1.6241991842057976e-002 -8.3732764425244177e+000 -4.9825593315549609e-002 -9.8752980718538574e-001 1.4933951309398580e-001 -3.0189942891342589e+000 -2.3929631075488872e-002 -1.4830193938966924e-001 -9.8865257170041976e-001 -3.2160841918332750e+000 0 0 0 1</transform>
        <rotation_covariance>2.9201267244704897e-008 1.9917633463540219e-008 1.5484264116575051e-009 1.9917633463540212e-008 5.2101318506962348e-008 -3.4984656864288386e-010 1.5484264116575055e-009 -3.4984656864288221e-010 1.3243919219993233e-008</rotation_covariance>
        <location_covariance>1.1295910829546713e-005 3.2288161486764346e-006 2.4336290525933714e-006 3.2288161486764346e-006 6.7747029743526271e-006 2.1546922880907544e-006 2.4336290525933714e-006 2.1546922880907544e-006 4.2155494465125021e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="12" sensor_id="1" label="Photo 12-12-2019, 11 50 16.jpg">
        <transform>9.9109558939615883e-001 -7.6210124544944038e-002 1.0918584888310780e-001 -7.7374795013061810e+000 -9.3897825284701836e-002 -9.8142363069637328e-001 1.6730467870789717e-001 7.5354498923704605e-002 9.4407261830244463e-002 -1.7606724291472636e-001 -9.7984059667178658e-001 -2.4898966285644124e+000 0 0 0 1</transform>
        <rotation_covariance>1.3181082503837745e-008 -4.9658740012025494e-010 -2.0613130458804494e-010 -4.9658740012025431e-010 4.3087165454236476e-008 -3.4639598728822767e-009 -2.0613130458804546e-010 -3.4639598728822767e-009 1.2125135351195845e-008</rotation_covariance>
        <location_covariance>8.8865644257174875e-006 4.6993083642353867e-008 4.9953715623075681e-007 4.6993083642353867e-008 3.8768994090332638e-006 3.0239241284385103e-007 4.9953715623075681e-007 3.0239241284385103e-007 2.3629506055155351e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="13" sensor_id="1" label="Photo 12-12-2019, 11 50 17.jpg">
        <transform>9.7878386878342560e-001 -1.3120768521631690e-001 1.5737433573974252e-001 -7.2737381290815870e+000 -1.6806179560458778e-001 -9.5346411728458891e-001 2.5032261166119368e-001 2.9819773168570323e+000 1.1720653167597378e-001 -2.7146034773221467e-001 -9.5528629663655962e-001 -1.7400627684778125e+000 0 0 0 1</transform>
        <rotation_covariance>1.9431134342159965e-008 -1.4097150291106358e-008 7.5582036068464161e-010 -1.4097150291106358e-008 4.0443529942387622e-008 -8.1860624888116143e-009 7.5582036068464078e-010 -8.1860624888116143e-009 1.3388016628181727e-008</rotation_covariance>
        <location_covariance>7.8220668121178370e-006 -1.5792363045224737e-006 -4.2487145158150261e-007 -1.5792363045224737e-006 4.1103317539378278e-006 -1.3682894621672561e-007 -4.2487145158150261e-007 -1.3682894621672561e-007 2.2741170789217661e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="14" sensor_id="1" label="Photo 12-12-2019, 11 50 18.jpg">
        <transform>9.7038435080313223e-001 -1.6079597933765027e-001 1.8027441511548115e-001 -6.7318442976259343e+000 -2.0551654507912617e-001 -9.4173143087886046e-001 2.6627966838193456e-001 5.8567608530451318e+000 1.2695338284237359e-001 -2.9544299809557084e-001 -9.4688767732037682e-001 -1.0413279325937221e+000 0 0 0 1</transform>
        <rotation_covariance>3.8451829856137123e-008 -2.3207724228269721e-008 4.7741788171115679e-009 -2.3207724228269724e-008 4.0130639588143737e-008 -1.0379207945718284e-008 4.7741788171115654e-009 -1.0379207945718284e-008 1.4715684045272833e-008</rotation_covariance>
        <location_covariance>7.2147109862188009e-006 -2.5256434781739810e-006 -7.4749274226892658e-007 -2.5256434781739810e-006 6.4928197863927636e-006 4.1046069518217648e-007 -7.4749274226892658e-007 4.1046069518217648e-007 3.0629398351412175e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="15" sensor_id="1" label="Photo 12-12-2019, 11 50 19.jpg">
        <transform>9.4183703317604783e-001 -2.4708160227402196e-001 2.2780185415365500e-001 -5.4587015014474760e+000 -3.1711655238524378e-001 -8.7781406956574370e-001 3.5899798255104998e-001 8.4676078376931105e+000 1.1126587590738707e-001 -4.1035733341824066e-001 -9.0511146483095262e-001 -8.0242093396186776e-001 0 0 0 1</transform>
        <rotation_covariance>7.5229006806843391e-008 -3.5639999659374072e-008 9.6539660855080628e-009 -3.5639999659374072e-008 6.4950271255204846e-008 -1.5761647526440760e-008 9.6539660855080628e-009 -1.5761647526440760e-008 2.1343032213230051e-008</rotation_covariance>
        <location_covariance>1.1359436870198948e-005 -4.3970186680141217e-006 -1.0999685907667756e-006 -4.3970186680141217e-006 1.3705442912649844e-005 2.0214492970167164e-006 -1.0999685907667756e-006 2.0214492970167164e-006 4.8585280988476625e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="16" sensor_id="1" label="Photo 12-12-2019, 11 50 20.jpg">
        <transform>9.2115801616947990e-001 -1.9452343899402175e-001 3.3708832808130079e-001 -3.6646495686587017e+000 -2.9261308207468095e-001 -9.1722758175049701e-001 2.7031675396632682e-001 7.3556137370944947e+000 2.5660376740309893e-001 -3.4764089943226589e-001 -9.0183164260102433e-001 3.6158367389235535e-001 0 0 0 1</transform>
        <rotation_covariance>6.1625508317129295e-008 -1.4728497462145200e-008 1.4618672297070569e-008 -1.4728497462145202e-008 2.9387699318747589e-008 -1.1189597019673988e-008 1.4618672297070568e-008 -1.1189597019673990e-008 2.0301589759284493e-008</rotation_covariance>
        <location_covariance>6.1855083620539144e-006 -1.5794199106439147e-006 -1.6722765479496618e-006 -1.5794199106439147e-006 8.7207486228908353e-006 2.0142792924310341e-006 -1.6722765479496618e-006 2.0142792924310341e-006 4.9240325953939410e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="17" sensor_id="1" label="Photo 12-12-2019, 11 50 21.jpg">
        <transform>9.2398073524538993e-001 -1.7831394019200519e-001 3.3832490246594443e-001 -4.0422114625768550e+000 -2.5123585821308037e-001 -9.4999570648671372e-001 1.8544190789772064e-001 4.9930602484716227e+000 2.8834032746621779e-001 -2.5634409763053179e-001 -9.2257658715505164e-001 -9.3260826990469547e-001 0 0 0 1</transform>
        <rotation_covariance>3.1780556192372011e-008 -8.1843947851755875e-009 4.8616447463402221e-009 -8.1843947851755859e-009 2.1652315838121405e-008 -7.6681945330236544e-009 4.8616447463402246e-009 -7.6681945330236544e-009 1.5106899136770812e-008</rotation_covariance>
        <location_covariance>3.7726227631570282e-006 -7.8622727771215623e-007 -1.1378201643143426e-006 -7.8622727771215623e-007 4.7257417534681429e-006 3.4664827915178455e-007 -1.1378201643143426e-006 3.4664827915178455e-007 2.7958728864380256e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="18" sensor_id="1" label="Photo 12-12-2019, 11 50 22.jpg">
        <transform>9.2428341289163307e-001 -1.6994202773259870e-001 3.4178923310064657e-001 -4.4508607359333521e+000 -2.2778128122556338e-001 -9.6407956147964291e-001 1.3662462098926495e-001 2.5274827793089432e+000 3.0629374883702121e-001 -2.0413306039775200e-001 -9.2979236019447453e-001 -2.1047324117573107e+000 0 0 0 1</transform>
        <rotation_covariance>1.5744641551227649e-008 -8.4748109100666035e-010 -9.1880544295312744e-010 -8.4748109100666045e-010 1.8285536702091776e-008 -7.1046148157346919e-009 -9.1880544295312620e-010 -7.1046148157346935e-009 1.2433573792213137e-008</rotation_covariance>
        <location_covariance>2.7293994726219634e-006 -1.2058303499370645e-008 -9.5159569020155007e-007 -1.2058303499370645e-008 2.7168955446820239e-006 -1.8799291841094653e-007 -9.5159569020155007e-007 -1.8799291841094653e-007 2.1803788158910615e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
      <camera id="19" sensor_id="1" label="Photo 12-12-2019, 11 50 23.jpg">
        <transform>9.2116771931621511e-001 -1.8007408163637662e-001 3.4499762029987824e-001 -4.3011994729157417e+000 -2.1969117619581444e-001 -9.7236069813270865e-001 7.9059849661957754e-002 -2.9631682395678643e-001 3.2122549710672571e-001 -1.4862031439102588e-001 -9.3526797344870616e-001 -3.1045155694704469e+000 0 0 0 1</transform>
        <rotation_covariance>1.4690115523845236e-008 5.5352598255905086e-009 -3.8782821609839897e-009 5.5352598255905095e-009 1.8450195646726343e-008 -5.3600942786820203e-009 -3.8782821609839922e-009 -5.3600942786820212e-009 1.0963294795490957e-008</rotation_covariance>
        <location_covariance>1.0507978324930479e-006 -1.2685847134401457e-007 -1.4437359657706481e-006 -1.2685847134401454e-007 2.3952670963053408e-006 -5.2863110122399679e-008 -1.4437359657706481e-006 -5.2863110122399686e-008 2.0052921187185627e-006</location_covariance>
        <orientation>6</orientation>
      </camera>
    </cameras>
    <reference>LOCAL_CS["Local Coordinates (m)",LOCAL_DATUM["Local Datum",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]]]</reference>
    <region>
      <center>-2.5859634612009001e+000 6.6474089378215062e+000 -1.5585711443826135e+001</center>
      <size>2.9805066935221355e+001 2.5763147989908852e+001 1.4299296824137372e+001</size>
      <R>-3.5045737518798281e-001 -8.8773158481274561e-001 -2.9851676921439518e-001 8.5453972732195216e-001 -4.3353481506400898e-001 2.8602345805185170e-001 -3.8332947004486040e-001 -1.5485540821445731e-001 9.1053737976090809e-001</R>
    </region>
    <settings>
      <property name="accuracy_tiepoints" value="1"/>
      <property name="accuracy_cameras" value="10"/>
      <property name="accuracy_cameras_ypr" value="10"/>
      <property name="accuracy_markers" value="0.005"/>
      <property name="accuracy_scalebars" value="0.001"/>
      <property name="accuracy_projections" value="0.5"/>
    </settings>
    <meta>
      <property name="AlignCameras/adaptive_fitting" value="false"/>
      <property name="AlignCameras/cameras" value=""/>
      <property name="AlignCameras/duration" value="6.095"/>
      <property name="AlignCameras/network_distribute" value="true"/>
      <property name="AlignCameras/reset_alignment" value="false"/>
      <property name="OptimizeCameras/sigma0" value="0.351760139619278"/>
    </meta>
  </chunk>
</document>

**Comment by uhlik** [comment]
looks like iphone report 2 sensors, but one is unused and is missing calibration data where i expect them. it is fixed now, reinstall addon.

**Comment by solosails** [comment]
You're the man! Thanks!
