### ISSUE TITLE
system time tracker trigger checkbox

### ISSUE THREAD

**Issue by brothermechanic** [uhlik/bpy#2]
Hello
GREAT, i really need this thing!
Thank you!
Can you more improove this addon? I mean trigger checkbox must be ready at hand, may be at header near blender logo on top.
What do you think?

**Comment by uhlik** [comment]
you're welcome!
there is simple panel in Properties (N key) in 3d view with button you need. simple enabled/disabled. adding it to header would be nice, even more logical place and convenient place, but modifying existing blender buttons is rather tricky and i prefer not to hack into default blender interface and possibly breaking something very easily in next release. making new panels is easy, and they can be collapsed to save space.

**Comment by brothermechanic** [comment]
Yesss!!!
I miss it!
Thank you!
