### ISSUE TITLE
Project point color TO target mesh uv texture

### ISSUE THREAD

**Issue by j2l** [uhlik/bpy#20]
Colorize option in project filter works fine with and I'd need to do reverse:
Write the (empty image) texture base on UV Map of a target mesh.
Is it possible to implement or help me do it?

**Comment by uhlik** [comment]
what is the point cloud source? if photogrammetry, you would get mesh with colors in any software that do any point cloud meshing. the idea here is, you scan, process to mesh, fix mesh shape and texture and if for some reason you want source point cloud to reflex that modifications you made, you project points to your mesh. vice versa you get from basically any photogrammetry software.

by the way, it will be much harder to implement, interpolate points to pixels how? say you have 100 points pointing to single pixel, what color will be? weight by distance? or something else? or how to interpolate single point over some pixel patch at the same time count on some influence of other points around? how many to consider? and some pixel manipulating external library will be a must. there are no tools to use in blender for that. sorry to disappoint you, but i have no time for that..

**Comment by j2l** [comment]
I understand your point.
