### ISSUE TITLE
Transfering Point Clouds from Open3D to Blender 2.80

### ISSUE THREAD

**Issue by makashy** [uhlik/bpy#21]
I exported a ply file from [Open3D](http://www.open3d.org/) library.  This is what I saw after importing to blender:

![Annotation 2019-12-27 212657](https://user-images.githubusercontent.com/8166046/71527216-a5ab8e80-28ef-11ea-9f56-59ca8a19b54e.jpg)

After lots of time struggling with Open3D, I found just by clicking **Enabling Edit Mode**, it will be fixed:

![Annotation 2019-12-27 213018](https://user-images.githubusercontent.com/8166046/71527317-1a7ec880-28f0-11ea-97a3-8f233b8cf989.jpg)

**Comment by YanWei123** [comment]
Can I have a sily question? Where can I find the point cloud visualizer addon?

**Comment by uhlik** [comment]
hi, can you send me an example ply to have a look?

**Comment by makashy** [comment]
here you are:
[GROUNDTRUTH.zip](https://github.com/uhlik/bpy/files/4006917/GROUNDTRUTH.zip)

**Comment by uhlik** [comment]
for display float32 is needed, your xyz data are declared as double and were loaded as it. fixed it in last commit. reinstall addon and it should work fine.
if i may suggest, save your data as binary ply, you will get much much faster load times and also your ascii ply has only 6 decimal spaces for those doubles..
