### ISSUE TITLE
How to create a point cloud ? 

### ISSUE THREAD

**Issue by furkan59** [uhlik/bpy#25]
Hi, 
I read the readme. But it only show how to edit existing point clouds. Is there any way to create point clouds ? 

For example at position ( 1,1,1) create a point with color ( 34,123,123) rgb ?

**Comment by uhlik** [comment]
you can generate from mesh: https://github.com/uhlik/bpy#generate or if you can code do it in python: https://github.com/uhlik/bpy#external-api, then export as ply in https://github.com/uhlik/bpy#export
it won't be much practical to do many points one by one with gui
