### ISSUE TITLE
Is it possible to add a code license?

### ISSUE THREAD

**Issue by Moult** [uhlik/bpy#26]
I am adding your point cloud visualiser to https://wiki.osarch.org/index.php?title=AEC_Free_Software_directory - is it possible to know what open-source license your code is under?

Cheers :) Your project is super valuable for as-built verification for BIM models in the construction industry!

**Comment by uhlik** [comment]
hi, it is GNU GPL Version 2 or later (same as blender itself) as stated on top: https://github.com/uhlik/bpy/blob/master/space_view3d_point_cloud_visualizer.py

**Comment by Moult** [comment]
Thank you :)
