### ISSUE TITLE
Conversion missing normals

### ISSUE THREAD

**Issue by JosephT722** [uhlik/bpy#27]
Converting LAS (Mobile Lidar Scanner) to PLY files (Binary) using cloud compare. Having issues with _Missing Vertex Normals_ when I click Draw....Am I missing something here
![blender](https://user-images.githubusercontent.com/62181584/76996387-6f464400-691f-11ea-9cff-5bee457924a2.PNG)
?

**Comment by uhlik** [comment]
hi, on your screenshot, there are position and color values, no normals. i can't help you with that

**Comment by JosephT722** [comment]
Duh I didn't even notice. my fault

**Comment by JosephT722** [comment]
here is my ply file renamed as a txt please help


![uhlk](https://user-images.githubusercontent.com/62181584/77102299-99af0480-69e6-11ea-959c-5972faf7728c.PNG)

**Comment by JosephT722** [comment]
I followed another guy on Ytube and he used a ascii format

**Comment by uhlik** [comment]
either your source data has no normals or cc skips them on reading. if you force it to write normals in file, you get all zeros which is useless. as you can read, vertex is defined in your ply as x,y,z,nx,ny,nz,red,green,blue,alpha,quality. where 3 values of normal should be, you have zeros.

by the way, ascii ply is much slower to read then binary and takes more disk space, so i recommend using binary

**Comment by JosephT722** [comment]
Awesome thanks....I will force normals

**Comment by uhlik** [comment]
by the way, why you need normals? pcv uses them for lighting and some more advanced filters

ps. i don't think i made it clear, you will have no warning about normals, but anything using them will not work as it should in pcv.. maybe some errors will go on top too

**Comment by JosephT722** [comment]
Thank you so much...I have been waiting for a replacement to Krakatoa.

Cheers
