### ISSUE TITLE
How to use blender itself to render the animation of the point cloud visualize by PCV?

### ISSUE THREAD

**Issue by KangchengLiu** [uhlik/bpy#29]
I wonder how to use blender itself instead of PCV to render the animation video of the point cloud visualize by PCV?

**Comment by enzyme69** [comment]
Let me try answering:

You can simply render it via the Render section from Point Cloud Visualizer side panel:

<img width="392" alt="Screen Shot 2020-03-24 at 1 54 41 pm" src="https://user-images.githubusercontent.com/3952687/77383438-048d8080-6dd7-11ea-99f6-c899e6ec9b5f.png">

- Save BLEND first
- setup Camera View
- set folder target
- render animation

**Comment by KangchengLiu** [comment]
@enzyme69，I mean render by blender software it self, not by PCV, thanks！

**Comment by enzyme69** [comment]
One method is to convert as Particles, instance Icosphere for each point cloud and then render using Cycles.

**Comment by KangchengLiu** [comment]
![pcv_render_result_028](https://user-images.githubusercontent.com/37166840/77385640-a86d3100-6dc3-11ea-9201-afe8bf06157a.png)
![pcv_camera_view_028](https://user-images.githubusercontent.com/37166840/77385645-ac00b800-6dc3-11ea-985f-54ed659d1068.PNG)

@enzyme69 Thanks for your reply. The problem I come across is the PCV rendering results is different from the original camera view and I don't know why, pls help, thanks!

**Comment by JosephT722** [comment]
Are you looking thru the camera? Or your viewport? It is not a PCV issue. 

[https://www.youtube.com/watch?v=ILqOWe3zAbk&list=PLa1F2ddGya_-UvuAqHAksYnB0qL9yWDO6&index=3&t=134s](url)

**Comment by KangchengLiu** [comment]
@JosephT722  I am look thru the camera, thanks!

**Comment by uhlik** [comment]
is the difference you speak about in point size in viewport vs render? it is resolution dependent. if you render larger image, points will have still the same pixels size. if you increase the size in render, it will look closer to viewport..

if you convert points to particles in Convert panel, in place of all points it will instance sphere and bake colors. then you can render with blender itself and if you switch particles to rendered display, what you will see in viewport is what you get in render
