### ISSUE TITLE
Possibility to actually generate mesh from point cloud?

### ISSUE THREAD

**Issue by enzyme69** [uhlik/bpy#30]
Thanks for the updated for Blender 2.8x version, this addon is very powerful and easy to use. 

I can see there is a way to generate point cloud from mesh, but I wonder if we can "remesh" from point cloud into surface mesh kind of like MeshLab?

**Comment by uhlik** [comment]
in python? would be much faster to do it in meshlab (or anywhere else) and import back to blender
