### ISSUE TITLE
Converting complete point cloud sequence to mesh

### ISSUE THREAD

**Issue by hossamshuk** [uhlik/bpy#32]
Hey, 

Is there anyway to convert my complete sequence to mesh without needing to go through each frame of the sequence and converting?

**Comment by uhlik** [comment]
not easy, limit scene frames to length of sequence, select object, preload sequence and run this from text editor. it will print frame numbers to console. and beware, it will eat your memory really fast, try first with small subset of points.
```
import bpy
c = bpy.context
l = c.view_layer
o = c.object
s = c.scene
fs = [i for i in range(s.frame_start, s.frame_end + 1, 1)]
for i, n in enumerate(fs):
    print(n)
    s.frame_set(n)
    bpy.ops.point_cloud_visualizer.convert()
    o.select_set(True)
    l.objects.active = o
```
