### ISSUE TITLE
Baking the vertex colors from point cloud to mesh

### ISSUE THREAD

**Issue by TheBricktop** [uhlik/bpy#33]
# Is there a way to bake point cloud colours to created mesh using for example emission?

**Comment by uhlik** [comment]
can you elaborate a bit? not sure if i understand

**Comment by TheBricktop** [comment]
Im asking about baking vertex colour to the texture of mesh.
The mesh is modelled, or meshed in meshlab and unwrapped.
Im thinking about transferring the colour data to the nearest point to the surface of the mesh or something similar.
![obraz](https://user-images.githubusercontent.com/3866030/83248899-0e03e200-a1a6-11ea-9dec-9194c5aa692a.png)

**Comment by fipes** [comment]
At a first glance I though the "projection" function is doing exactly this: projecting points color onto a meshs texture. It's only for filtering points, but it would be nice to have such a feature.

**Comment by uhlik** [comment]
> Im thinking about transferring the colour data to the nearest point to the surface of the mesh or something similar.

that meshlab filter requires both meshes to have faces.. no inspiration there, but what about instead of texture, use vertex colors on target mesh? that can be easier to start with, but it is sufficient for such use? i don't know, i do textures in metashape using original photos..

**Comment by uhlik** [comment]
alright, it was not that difficult after all. still needs some polishing but basically done. it will go to 1.0+ version.
![transfer-uv](https://user-images.githubusercontent.com/188483/83350290-8059fb00-a33b-11ea-9590-a0d877a8dd4b.jpg)

**Comment by TheBricktop** [comment]
@uhlik that is not true, baking intentionally can be used with pure point cloud with color but the bug falsely required source to have mesh. They fixed it up in nightly builds and I'm confirming it works.
