### ISSUE TITLE
Enhancement of Blender's OpenGL renderer

### ISSUE THREAD

**Issue by SBCV** [uhlik/bpy#34]
I've added a [proposal ](https://blender.community/c/rightclickselect/tGfbbc/) to enhance Blender's OpenGL renderer, such that it renders the full 3D View including points drawn with GPU module to disk.

I'm posting this here, since this feature would be beneficial for users of the Point Cloud Visualizer as well. You can vote for the proposal [here](https://blender.community/c/rightclickselect/tGfbbc/). If you think this is the wrong place this information, feel free to close this issue.

**Comment by uhlik** [comment]
you can add to proposal that surprisingly, `Window > Save Screenshot` renders custom things as they appear on screen, so for consistency `3D View > View > Viewport Render Image` should do that as well :)
