### ISSUE TITLE
Question about accessing add-on...

### ISSUE THREAD

**Issue by JakubPelka** [uhlik/bpy#36]
Hi, I wonder is the only option to test Point Cloud Visualiser to buy it via blender market?
in the python file you start with lines that it is a free software - https://raw.githubusercontent.com/uhlik/bpy/master/space_view3d_point_cloud_visualizer.py, but maybe I miss it somehow, how to download addon to test it.
If it will work well, then of course I would buy it to say thank you for your effort.
Will be glad for answer.

**Comment by uhlik** [comment]
hi, you can test PCV 0.9.x directly from this repository. you even linked correct file? on repo main page you click `Code` > `Download ZIP`, unzip, and install `space_view3d_point_cloud_visualizer.py` from `blender > preferences > addons > install from file`. 1.x can load points subsets, takes less memory, some operations are faster, a few new shaders, more organized ui. most of the functionality is the same.
