### ISSUE TITLE
Point Cloud Visualizer no longer works in blender 2.8

### ISSUE THREAD

**Issue by villajuvius** [uhlik/bpy#4]
First of all, thanks you so much for this amazing plugin.

I run into an issue with the blender 2.8 version, the pointcloud can't be draw into the scene. Have you an idea of what can cause this problem ?

**Comment by uhlik** [comment]
hi, it have to be that 2.8 is not backward compatible. one of the main changes is the new viewport and with that also minimal opengl version change and also very likely corresponding python api.. personally i keep out of 2.8 until it will be considered stable.. but i am going to update the addon after that
