### ISSUE TITLE
'ShaderNodeBsdfPrincipled' object has no attribute 'image'

### ISSUE THREAD

**Issue by jackwolfwolf** [uhlik/bpy#40]
Hey Guys,
When i try to generate points using:
Souce- Surface 
Algo- Weighted randow
colors-UV texture 
I get this message 'ShaderNodeBsdfPrincipled' object has no attribute 'image'
Any ideas how to resolve this ?
Thanks,
J

**Comment by uhlik** [comment]
hi, on mesh, make material, add image texture node and load image, then select image texture node in material editor so pcv know which one to use, from docs: `UV Texture - Generate colors from active image texture node in active material using active UV layout`

**Comment by sharoseali** [comment]
> hi, on mesh, make material, add image texture node and load image, then select image texture node in material editor so pcv know which one to use, from docs: `UV Texture - Generate colors from active image texture node in active material using active UV layout`

Hi! I want to map texture from png image on the mesh using python. Any help  to do that.

**Comment by anthonySemaan01** [comment]
Hello,
I am facing the same problem... I want to generate colors from a mesh having PBR textures. The add-on force me to select and activate a specific image texture, even though I want to generate from the BSDF node.

Anyone can help me here?

**Comment by uhlik** [comment]
it needs to read raw image rgba pixels, bsdf node is not providing that. you can use bake functionality in cycles to get single image from multiple or with shading aplied. https://docs.blender.org/manual/en/dev/render/cycles/baking.html
