### ISSUE TITLE
Problem with render of png

### ISSUE THREAD

**Issue by VitaliiHm** [uhlik/bpy#44]
Hi, i have some problems with render, the picture is black and there is nothing on it.
I tried to change the light but nothing worked, i don't know what else to do.
I have the latest official version of blender.

![pcv_render_000](https://user-images.githubusercontent.com/75545858/101265152-6b787d00-374d-11eb-8178-0d5987178ecb.png)
![image](https://user-images.githubusercontent.com/75545858/101265256-9bc01b80-374d-11eb-90e1-3bd368f2ec8f.png)

**Comment by uhlik** [comment]
hi, there was an blender api change in blender 2.91, 0.9.x version is fully compatible up to blender 2.82. should work with slightly off colors up to 2.90
