### ISSUE TITLE
render not vissible

### ISSUE THREAD

**Issue by wun11** [uhlik/bpy#47]
Hello,
I am trying to work with your PCV add-on, I have the blender version 2.92. on mac, but from some reason, when I hit render (single image or animation) the outcome png files are only grey (blank), no image shows up - I am a complete beginner with blender, but I followed all instructions I could find (attached the cloud to empty object, set active camera seeing the cloud), created some simple movement of the camera, I can't figure out what I am doing wrong, it must be some stupid mistake :).

**Comment by uhlik** [comment]
hi, i don't think you are doing anything wrong. for blender 2.92 you need PCV 1.+ from blendermarket or for PCV 0.9.x from repository you need blender 2.81a - i think it's the last blender version working, there were several api changes (color management, rendering, some depth sorting issues as i remember) and i no longer develop repository PCV. but if you have PCV 1.+, drop me line on blendermarket and i can help you with that there.

**Comment by wun11** [comment]
aha, ok. Well, I have the blendermarker version. I bought it in January this year, was there some newer version from that time? Or is it possible to upgrade the add-on?

**Comment by uhlik** [comment]
current version is 1.7.0, you should be able to download it your account > orders. update PCV, try it, and if that doesn't work, write me on blendermarket

**Comment by wun11** [comment]
It works! :) thank you

**Comment by Linusnie** [comment]
hi, as far as I can tell the regular Render->Render Animation tool in Blender is not supported as the pointcloud will not be visible (even in Blender 2.8), please let me know if I'm wrong on that. You can however click "Animation" in the Point Cloud Visualizer tab to generate a .png file for each frame with transparent background which you can combine into an animation with another tool.

**Comment by uhlik** [comment]
correct, pcv render is separate process. blender (until very recently and still very experimental feature) cannot render colored points without any meshes attached to them

**Comment by qixuema** [comment]
I see, thanks!
