### ISSUE TITLE
Add On not showing up.

### ISSUE THREAD

**Issue by jackwolfwolf** [uhlik/bpy#52]
Hey Guys, Any idea why the Add On will not apear in blend 2.83?
No error message. Looks like everything worked.

"Modules Installed () from 'C:\\Users\\*******\\Downloads\\bpy-master.zip' into 'C:\\Users\\********\\AppData\\Roaming\\Blender Foundation\\Blender\\2.83\\scripts\\addons'"

Thanks,
J

**Comment by uhlik** [comment]
hi, this is repository of multiple addons, if you download whole repo as zip and try to install it, blender will not understand it. extract files and install one by one which you need..

**Comment by jackwolfwolf** [comment]
Thanks, works perfectly. Great tools!
