### ISSUE TITLE
Where is the Import panel?

### ISSUE THREAD

**Issue by pflani** [uhlik/bpy#53]
Hello,
I want to import a .csv file and am unable to find the import sub-panel described in the documentation:
![image](https://user-images.githubusercontent.com/78821916/130513503-f8aaad3c-b62b-4361-bbff-cb181ab88826.png)

Does the PCV version I just downloaded no longer have that ability? I assume there should be an "Import" drop down 
![image](https://user-images.githubusercontent.com/78821916/130513787-b896d84a-a84e-449a-8e6f-8ed0b44d6db5.png)

Thank you!

**Comment by uhlik** [comment]
hi, text based formats import is feature of PCV 1+ available on blender market.
