### ISSUE TITLE
mapping png file on a mesh as texture using python

### ISSUE THREAD

**Issue by sharoseali** [uhlik/bpy#56]
HI, I have a mesh as obj form and I want to use it as a texture on that mesh using python. How can do that? Any help regarding this. Thanks

**Comment by uhlik** [comment]
hi, i have no idea what are you talking about. use mesh as texture? how? sorry

**Comment by sharoseali** [comment]
> hi, i have no idea what are you talking about. use mesh as a texture? how? sorry

sorry! I re-edit the comment. I mean I want to put texture on a mesh and texture is a png image. [here](https://drive.google.com/file/d/1x-j5vv77B73YYsZ5smWFabvQrFg5ZkSX/view?usp=sharing) is my data Thanks.

**Comment by uhlik** [comment]
is it related to any of addons? is not look in blender manual: https://docs.blender.org/manual/en/dev/

**Comment by sharoseali** [comment]
> is it related to any of addons? is not look in blender manual: https://docs.blender.org/manual/en/dev/

I want to do (texture mapping ) using python, not from blender or third part tool, so if I use **bpy** then what could be the possible approach to do this.

**Comment by uhlik** [comment]
this is just a repository of a few of **my** scripts **for** blender. i can't help you
