### ISSUE TITLE
Point Cloud Visualizer: Only generating points within camera view (i.e backface points are culled)

### ISSUE THREAD

**Issue by ASeau** [uhlik/bpy#57]
Hi, I was trying to simulate an actual point cloud scan and was wondering if there's a way to only generate points on the surfaces that are currently rendered in view of a scanner/camera? I have tried using both the "Use Viewport Points" and also the "Visible Points Only" in the export section. Both exports seem to have all the points (in view and also back face of the camera). 

I understand the functions are working as intended but any advice for a workaround solution would be helpful.

**Comment by uhlik** [comment]
hi, if you write here i suppose you are using 0.9.x version, so, one workaround came to my mind, you can generate points on mesh, then duplicate mesh, move a bit in direction you are looking so it overlaps points at back side of original mesh and points in front are outside of it and then use boolean filter on points from pcv to remove points in back.
