### ISSUE TITLE
Clip to a cube does not work

### ISSUE THREAD

**Issue by ttkrpink** [uhlik/bpy#58]
Hi, Author,

I followed the instructions on [YouTube](https://www.youtube.com/watch?v=eXct_7k779Q). But the Clip to a cube function does not work. If I enabled the Clipping Planes Shader, the whole point cloud disappeared. I tried 2.80,2.97 and 3.0. 

So, what could be the problem? The point cloud does not have normals. I used Meshlab to compute the normals. The attached txt file is a ply file exported from Meshlab with normals.

Thanks for your help.

![image](https://user-images.githubusercontent.com/2522889/146678717-01fdbe84-2d7b-4b89-a2a3-677968bb32e9.png)
![image](https://user-images.githubusercontent.com/2522889/146678736-e3773a93-09ff-44ff-93bb-42f4c8718e59.png)
[raptor_w_normal.txt](https://github.com/uhlik/bpy/files/7740978/raptor_w_normal.txt)

**Comment by uhlik** [comment]
that's a bug in this obsolete version, points container object have to be at 0,0,0 when you click set planes operator
