### ISSUE TITLE
Error Converting a Point Cloud to Objects ver. 0.8.11 in Blender 2.8 2019-05-31

### ISSUE THREAD

**Issue by BillMudge** [uhlik/bpy#6]
To Whom It May Concern:

I can visualize (i.e., draw) the attached .ply file without problems but I cannot convert it to cubes or ico spheres, etc., without errors:

bpy.ops.object.delete(use_global=False)
Deleted 1 object(s)
bpy.ops.object.empty_add(type='PLAIN_AXES', location=(0, 0, 0))
bpy.context.space_data.recent_folders_active = 1
bpy.context.object.point_cloud_visualizer.mesh_type = 'ICOSPHERE'
Traceback (most recent call last):
  File "/Users/wmudge/Library/Application Support/Blender/2.80/scripts/addons/Point Cloud Visualizer.py", line 1732, in execute
    instancer = PCMeshInstancer(**d)
  File "/Users/wmudge/Library/Application Support/Blender/2.80/scripts/addons/Point Cloud Visualizer.py", line 229, in __init__
    self.mesh.show_double_sided = False
AttributeError: 'Mesh' object has no attribute 'show_double_sided'

location: <unknown location>:-1

FYI:  The attached Galaxy file is a public domain project from SketchFab.

[Galaxy.zip](https://github.com/uhlik/bpy/files/3293229/Galaxy.zip)

Thanks for your attention to this problem.

**Comment by uhlik** [comment]
blender api changed, already fixed it, please reinstall from repo
