### ISSUE TITLE
GPUShader.uniform_float: uniform alpha_radius not found

### ISSUE THREAD

**Issue by fishbotics** [uhlik/bpy#60]
Hi,

I'm using the Pointcloud rendering tool and I keep seeing this error when I hit render that says `GPUShader.uniform_float: uniform alpha_radius not found`. I am using Blender 3--could that be the issue?

Thanks!

**Comment by fishbotics** [comment]
Here is an example file (I had to zip it for Github to accept it
[full_view.zip](https://github.com/uhlik/bpy/files/7910312/full_view.zip)
)

**Comment by uhlik** [comment]
hi, pcv 2.0 is compatible with blender 3.0, pcv 0.9 here is fully compatible with blender 2.81 and up to 2.83 kinda works with incorrect colors
