### ISSUE TITLE
Conversion to Animation with original point cloud colour 

### ISSUE THREAD

**Issue by henrymorgan95** [uhlik/bpy#61]
I am trying to animate the pointcloud using blender forces but if I convert the ply to a mesh, the colour is correct and baked into each 'cube' (for example) however it cannot be animated using forces. Likewise when I convert the ply to a particle system - it can be animated but the colours are missing. 

Am I missing a step in either process or is this not possible yet for the addon to animate a coloured mesh conversion or colour a particle system? Loving it so far, hopefully it is possible!

**Comment by uhlik** [comment]
if i remember right, particles take color from baked uv texture on emitter. convert operator should do this for you. but color will be visible only in render (cycles).

**Comment by uhlik** [comment]
if you are using pcv from this repository, go pcv > convert > set type to particle system > click convert. all will be done in one click. points will be converted to emitter mesh, added particle system to emit single particle from each face, then points colors will be baked to uv texture on emitter so particles get color and if i remember right event material for instance will be added using that color attribute. try it, you will see what you get. but it may not work in newer blender. blender 2.81 was the last version pcv 0.9.x was working correctly and was tested on.
