### ISSUE TITLE
Rendering stills or animation get Blender unresponsive

### ISSUE THREAD

**Issue by Albanbrice** [uhlik/bpy#62]
Hello,
Trying out the 2.0 prerelease with Blender 3.1.0 :
load a regular 300Mb pointcloud PLY file, everything looks nice, but after the render completion (either still or animated), it wasn't possible to have any action in Blender. On mouse enter the 'render' button blinks. No way to open any menu or to browse the 3d viewport. I had to brute force quit Blender. 
Thanks in advance for any hints... really wanted to use PCV with Blender 3 in production. Regards
Alban

**Comment by uhlik** [comment]
hi, please, drop me a line on blendermarket pcv page while logged in using support button and we can continue there
