### ISSUE TITLE
PCV 2.0 "Load" panel differences from documentation

### ISSUE THREAD

**Issue by rjnskl** [uhlik/bpy#65]
Apologies if I just missed a setting somewhere, but I've installed the most recent version of Point Cloud Visualizer available on Blender Market (2.0 / 1.999.10), installed all the optional libraries. But my "Load" panel has different options than the guide: https://jakubuhlik.com/docs/pcv/docs.html#manual-use

<img width="419" alt="Screen Shot 2022-04-25 at 10 53 55 PM" src="https://user-images.githubusercontent.com/840767/165211079-903998a2-8ccb-4c1b-b4fa-fd6fffeadb9c.png">

I'm on a Macbook Pro, Big Sur 11.6.2.

**Comment by uhlik** [comment]
hi, docs are still for 1.x version, sorry. that is why i mark 2.0 as alpha. but it is perfectly stable, only a few things are waiting to be added and docs before final 2.0. please use get support button on blendermarket if you have more questions, thanks!
