### ISSUE TITLE
Depth from ply file

### ISSUE THREAD

**Issue by rebecca0011** [uhlik/bpy#68]
I import a UAV scene into blender and try to get depth from the scene using compositing nodes.
But I got nothing from scene. It seems that the scene have no depth information. So how can I get depth from the imported ply fily?
<img width="808" alt="Snipaste_2022-06-15_17-23-09" src="https://user-images.githubusercontent.com/49330159/173793602-8e7aa2d7-a705-4c94-8278-7cfb9f08e136.png">

**Comment by uhlik** [comment]
hi, this 'depth' is just a shader that try to color points by distance from camera. and is also view dependent. in pcv 2.0 you could make scalar value from point z location in some defined range, then convert to geometry nodes and use that scalar as you wish, but this pcv version does not support anything like that. and if your 'depth' is scalar value on points this pcv version cannot read that. scalars are supported in pcv 2.0
