### ISSUE TITLE
Invalid syntax in CARBON_properties class (?)

### ISSUE THREAD

**Issue by CUBICinfinity** [uhlik/bpy#7]
When I try to activate the carbon_tools.py addon I get this error:
![image](https://user-images.githubusercontent.com/19354800/60063625-d13c8a80-96ba-11e9-8257-784d8661db10.png)

I'm not an expert with python. What does the `stuff: SomethingProperty(x="yoda", y="ceasar", )` syntax do? Is this something that only works in Python 2.7?

**Comment by jiunyen-ching** [comment]
Same problem for me when I try to activate view3d_point_cloud_visualizer.py

I am using Blender 2.79b on a Ubuntu 14.04
![view3d_point_cloud_visualizer](https://user-images.githubusercontent.com/25114361/60070704-2673ad00-974a-11e9-9d91-7ac995735169.jpg)

**Comment by uhlik** [comment]
both of you are trying to load blender 2.80 addon in 2.79, declaring properties has different syntax in 2.80

**Comment by CUBICinfinity** [comment]
Thanks!

**Comment by jiunyen-ching** [comment]
Got it! Will switch to Blender 2.80
