### ISSUE TITLE
Missing vertex normals

### ISSUE THREAD

**Issue by MariaMel98** [uhlik/bpy#72]
Hello. I have installed the point cloud visualizer add on and I'm trying to load some .ply files that I have downloaded. I get the error "missing vertex normals".  Has anybody had this problem?

**Comment by uhlik** [comment]
hi, that means that data you loaded don't have normals on points. it shows when for somehing normals are needed. like some shaders. shows when without normals it can't do something. only a warning, that's all.

**Comment by MariaMel98** [comment]
Ok but when I press Draw I don't see anything. Do I need the normals for that? If no, why doesn't it show the file? I'm attaching a screenshot for reference.
![Στιγμιότυπο οθόνης (82)](https://user-images.githubusercontent.com/105556892/186348513-4f4316fc-28e3-49fc-987b-6a0172bd0e6e.png)
?
