### ISSUE TITLE
export ply from external API

### ISSUE THREAD

**Issue by anthonySemaan01** [uhlik/bpy#74]
Hello,
How can we use the external API to export generated point clouds from the mesh?
I want to export the ply file and provide a name for the file without using the GUI.

Thank you for your help

**Comment by uhlik** [comment]
if you are using 0.9, why don't you look at source? here is export operator: https://github.com/uhlik/bpy/blob/master/space_view3d_point_cloud_visualizer.py#L6107 make a modification as you wish so it does what you want, or make a new operator, import some classes from pcv and copy parts you need from original operator..

if you are using 2.0, please, write me on blendermarket.
