### ISSUE TITLE
Point Cloud Visualizer: Coloriizer not working on Parallel projection

### ISSUE THREAD

**Issue by funatsufumiya** [uhlik/bpy#75]
Colorizer of Point Cloud Visualizer is not working especially gradation on Parallel projection mode. How can I fix this?

<img width="1440" alt="screenshot_2022-10-27_15_35_11" src="https://user-images.githubusercontent.com/3406260/198209291-283e4f1e-bd48-49a3-9eea-ef1b4e82af0c.png">

<img width="1440" alt="screenshot_2022-10-27_15_35" src="https://user-images.githubusercontent.com/3406260/198209988-0661e790-1043-4880-8ff1-5bbb17b94692.png">

**Comment by uhlik** [comment]
hi,
this has been fixed way back in 1.0. to fix in this version, you would need to rewrite related shader by yourself.
pcv 0.9 is available here, but not developed anymore. new development and compatibility with new blender versions is in blender market pcv.

and one note, pcv 0.9 is fully compatible only with blender 2.81, in later blender versions point colors on screen are not color managed and looks wrong, opengl render to image not working and maybe many other problems related to changes in blender api. pcv 0.9 uses deprecated blender api. most likely will stop working in blender 3.4 where that api is going to be removed from blender.

**Comment by funatsufumiya** [comment]
@uhlik Thank you for the response. I confirmed this solved with v2.0. I didn't notice that this OSS uploaded version is older than Blender Market one. Thank you.

<img width="1440" alt="screenshot_2022-10-27 18 59" src="https://user-images.githubusercontent.com/3406260/198255272-baae5ebc-6a37-4363-883f-b00a8eb541d7.png">

<img width="1440" alt="screenshot_2022-10-27 18 58" src="https://user-images.githubusercontent.com/3406260/198255300-7778dcaa-812c-4378-93e6-b81c986d705c.png">

**Comment by uhlik** [comment]
good. only next time write me on blender market for support please, there is button on right sidebar on pcv store page
