### ISSUE TITLE
Point Cloud Visualizer: Semi-Transparent Material view

### ISSUE THREAD

**Issue by funatsufumiya** [uhlik/bpy#76]
I'd like to interact with objects which has semi-transparent material, but currently semi-transparent is not working with Point Cloud Visualizer. Any advices are welcome to achieve this...

<img width="1440" alt="screenshot_2022-10-27 17 40" src="https://user-images.githubusercontent.com/3406260/198236656-d363ebc4-9ff9-4d0b-8a50-e0f3411b804e.png">

<img width="1440" alt="screenshot_2022-10-27 17 40_2" src="https://user-images.githubusercontent.com/3406260/198236707-8c2f9b3a-bf11-4691-9bfc-4b8061288bb5.png">

**Comment by uhlik** [comment]
and if you lower alpha of points? main panel bellow point size. would look better?

**Comment by uhlik** [comment]
ah, ok, it will not, because of depth test. what you want requires to draw semi-transparent points on top of everything in scene. like in pcv 2.0 on screenshot
![trasparent](https://user-images.githubusercontent.com/188483/198256563-528444cd-6e91-4722-a65a-3def91c64a8b.png)

**Comment by funatsufumiya** [comment]
@uhlik 
That's true. Lower alpha points makes the "all" points lower alpha. and changing point size is the same.
I'd like to check occlusion with objects like depth tests.

**Comment by uhlik** [comment]
like what is depth tested to be under existing geometry in scene drawn with lower alpha? hm. dunno if even possible with blender api. pcv 2.0 has xray shader that could be a bit helpful in such case..

![xray](https://user-images.githubusercontent.com/188483/198259068-c60f0b93-5d5a-4651-9b47-bda57b9861d8.png)
