### ISSUE TITLE
Render point cloud doesn't work

### ISSUE THREAD

**Issue by LisaDieterle** [uhlik/bpy#78]
Hi, I'm trying to render my point cloud but the png is always empty. Do you know how to fix this?

**Comment by uhlik** [comment]
hi, use blender 2.81 as it says in readme. only pcv from blender market is updated and supported

**Comment by LisaDieterle** [comment]
thx so much. is there a way to render point cloud and the 3d models in the scene together?

**Comment by uhlik** [comment]
not in this old version..
