### ISSUE TITLE
Addon for Point Cloud Visualizer (Blender 2.80) does not work....

### ISSUE THREAD

**Issue by enzyme69** [uhlik/bpy#8]
Do I need GPU for this to work? I tested on Blender 2.80 Mac CPU only...

```
Exception in module register(): /Users/jimmyg/Library/Application Support/Blender/2.80/scripts/addons/view3d_point_cloud_visualizer.py
Traceback (most recent call last):
  File "/Users/jimmyg/Downloads/blender-2.80.0-git20190503.b331515d2e47-x86_64/blender.app/Contents/Resources/2.80/scripts/modules/addon_utils.py", line 384, in enable
    mod.register()
  File "/Users/jimmyg/Library/Application Support/Blender/2.80/scripts/addons/view3d_point_cloud_visualizer.py", line 2150, in register
    bpy.utils.register_class(cls)
RuntimeError: Error: Registering panel class: parent 'PCV_PT_panel' for 'PCV_PT_convert' not found


```

**Comment by enzyme69** [comment]
NOTE: The Blender 2.79 version works fine without issue.

**Comment by uhlik** [comment]
today's mac os x build works (almost) as it should, also the error looks incomplete, would you please replace addon in "/Users/jimmyg/Library/Application Support/Blender/2.80/scripts/addons/" with freshly downloaded and try again with fresh blender 2.80? also would help if you befor trying start blender from terminal, right click Blender.app, Show package contents, go Contents/MacOS and double click "Blender" executable, it should open in terminal, if some error happen, paste full terminal output

**Comment by enzyme69** [comment]
I download the latest one just now and the addon works now on Blender 2.80 latest version! Thanks~
