### ISSUE TITLE
Point Cloud Visualizer questions....

### ISSUE THREAD

**Issue by enzyme69** [uhlik/bpy#9]
I manage to get the Point Cloud Visualizer addon works great in Blender 2.79 but a couple of questions arise:
- Can we load a sequence of PLY or .... limited to only one at a time?
- Is it possible to source and query this loaded PLY data using BPY? I wanted to use it for other purpose.

Thanks!

**Comment by enzyme69** [comment]
Ah, I realized I could have multiple Empty and each Empty can be assigned a different visualizer. Would it be heavy once I have like 100-200 Point Cloud? 

Still wondering if it is possible to just "plug" or quickly replace path (somewhat) so that it changes based on frame number, practically load and update per frame as sequence?

**Comment by uhlik** [comment]
first of all 2.79 version is slow and pretty basic, 2.80 version is full rewrite with more features..
but, 1. you can display different cloud on different empty object with different PCV instance, in theory as many as you want, but 2.79 version uses very slow drawing functions..
2. like let it load ply and with different python script read loaded points? you can copy BinPlyPointCloudReader class from addon itself, it is pretty self-contained
ps. caught me in the middle of writing :)

**Comment by enzyme69** [comment]
Thanks @uhlik This is totally awesome and what I needed! Best PLY reader for Blender. Will spread the news. Cheers!

I am now using Blender 2.80 version and yes I got the PLY loaded nicely! Loading PLY sequence is still not quite clear.

I wanted to try to port this to Sverchok nodes or animation nodes, will check BinPlyPointCloudReader that you are talking about....

**Comment by enzyme69** [comment]
With 2.80, seems like we cannot easily show and hide the point cloud using Visibility of Empty. Unlike 2.79.

What would be your advice for me to get the sequence of PLY to load and unload on every frame?

**Comment by enzyme69** [comment]
If I run command like this:
bpy.data.objects['Empty'].point_cloud_visualizer.filepath = '/Users/jimmyg/Downloads/2019-06-25--14-08-06/PLYs/0000000.ply'

I was hoping for the Point Cloud Viewer to auto update, but it does not. Only if I reload the Blend and manually hit erase and draw, then it updates. Unless there is another way to force update?

**Comment by uhlik** [comment]
- in 2.80 version, there is even better ply loader, a lot faster, but needs numpy
- like hide in outliner or H key? didn't know that :) will check and will see
- about loading each frame different ply as it is now, i don't thinks so. adding viewport drawing handlers is tricky
- changing path will not work, but you could simulate what is happening when you do it with buttons by calling single operators, like, hide(), change path, load(), draw() will be kinda slow, but might work

**Comment by uhlik** [comment]
- regarding ply loader, best to use 'PlyPointCloudReader' class from 2.8 PCV version, handles binary and ascii ply files as well all with numpy for speed

**Comment by enzyme69** [comment]
Ok I will try might reopen the case :] Ideally if your add-on can open the data for SVerchok or Animation Nodes... but I supposed I should try investigate first. Thanks for your time!

**Comment by uhlik** [comment]
sounds like a interesting idea, but i have no experience with sverchok etc. i found doing my generative experiments in just python easier, but let me know if you have something concrete
